import type { Metadata } from 'next';
import { Public_Sans } from 'next/font/google';
import './globals.css';
import { cn } from '@/lib/cn';
import { Toaster } from '@/components/ui/sonner';

const fontFamily = Public_Sans({
	weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
	subsets: ['latin-ext'],
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body className={cn(fontFamily.className, 'fz-preset-4 bg-background')}>
				{children}
				<Toaster
					toastOptions={{
						className: 'bg-theme-white text-theme-gray-900',
					}}
				/>
			</body>
		</html>
	);
}
